"""Verified dlt Slack source vendored for the personal assistant template."""

from __future__ import annotations

from functools import partial
from typing import Any, Iterable, Literal, Optional

import dlt
from dlt.common.typing import TAnyDateTime, TDataItem
from dlt.sources import DltResource
from pendulum import DateTime

from .helpers import SlackAPI, ensure_dt_type
from .settings import (
    DEFAULT_DATETIME_FIELDS,
    DEFAULT_START_DATE,
    MAX_PAGE_SIZE,
    MSG_DATETIME_FIELDS,
)


@dlt.source(name="slack", max_table_nesting=2)
def slack_source(
    page_size: int = MAX_PAGE_SIZE,
    access_token: str = dlt.secrets.value,
    start_date: Optional[TAnyDateTime] = DEFAULT_START_DATE,
    end_date: Optional[TAnyDateTime] = None,
    selected_channels: Optional[list[str]] = dlt.config.value,
    table_per_channel: bool = True,
    replies: bool = False,
    include_private_channels: bool = False,
) -> Iterable[DltResource]:
    """The verified Slack dlt source generated by `dlt init slack duckdb`."""

    end_dt: Optional[DateTime] = ensure_dt_type(end_date)
    start_dt: Optional[DateTime] = ensure_dt_type(start_date)
    write_disposition: Literal["append", "merge"] = "append" if end_date is None else "merge"

    api = SlackAPI(
        access_token=access_token,
        page_size=page_size,
    )

    def get_channels(
        slack_api: SlackAPI,
        selected_channels: Optional[list[str]],
        include_private_channels: bool = False,
    ) -> tuple[list[TDataItem], list[TDataItem]]:
        channels: list[TDataItem] = []
        conversation_types = (
            "public_channel,private_channel,mpim" if include_private_channels else "public_channel"
        )

        for page_data in slack_api.get_pages(
            resource="conversations.list",
            response_path="$.channels[*]",
            datetime_fields=DEFAULT_DATETIME_FIELDS,
            params={"types": conversation_types},
        ):
            channels.extend(page_data)

        if selected_channels:
            fetch_channels = [
                c for c in channels if c["name"] in selected_channels or c["id"] in selected_channels
            ]
        else:
            fetch_channels = channels
        return channels, fetch_channels

    channels, fetched_selected_channels = get_channels(
        api, selected_channels, include_private_channels
    )

    @dlt.resource(name="channels", primary_key="id", write_disposition="replace")
    def channels_resource() -> Iterable[TDataItem]:
        yield from channels

    @dlt.resource(name="users", primary_key="id", write_disposition="replace")
    def users_resource() -> Iterable[TDataItem]:
        for page_data in api.get_pages(
            resource="users.list",
            response_path="$.members[*]",
            params=dict(include_locale=True),
            datetime_fields=DEFAULT_DATETIME_FIELDS,
        ):
            yield page_data

    def get_messages(
        channel_data: dict[str, Any], start_date_ts: float, end_date_ts: float
    ) -> Iterable[TDataItem]:
        params = {
            "channel": channel_data["id"],
            "oldest": start_date_ts,
            "latest": end_date_ts,
        }

        for page_data in api.get_pages(
            resource="conversations.history",
            response_path="$.messages[*]",
            params=params,
            datetime_fields=MSG_DATETIME_FIELDS,
            context={"channel": channel_data["id"]},
        ):
            yield page_data

    def get_thread_replies(messages: list[dict[str, Any]]) -> Iterable[TDataItem]:
        for message in messages:
            if message.get("thread_ts", None):
                params = {
                    "channel": message["channel"],
                    "ts": ensure_dt_type(message["thread_ts"], to_ts=True),
                }

                for page_data in api.get_pages(
                    resource="conversations.replies",
                    response_path="$.messages[*]",
                    params=params,
                    context={"channel": message["channel"]},
                ):
                    yield page_data[1:]

    @dlt.resource(
        name="messages",
        primary_key=("channel", "ts"),
        columns={"blocks": {"data_type": "json"}},
        write_disposition=write_disposition,
    )
    def messages_resource(
        created_at: dlt.sources.incremental[DateTime] = dlt.sources.incremental(
            "ts",
            initial_value=start_dt,
            end_value=end_dt,
            allow_external_schedulers=False,
        ),
    ) -> Iterable[TDataItem]:
        start_date_ts = ensure_dt_type(created_at.last_value, to_ts=True)
        end_date_ts = ensure_dt_type(created_at.end_value, to_ts=True)
        for channel_data in fetched_selected_channels:
            yield from get_messages(channel_data, start_date_ts, end_date_ts)

    def per_table_messages_resource(
        channel_data: dict[str, Any],
        created_at: dlt.sources.incremental[DateTime] = dlt.sources.incremental(
            "ts",
            initial_value=start_dt,
            end_value=end_dt,
            allow_external_schedulers=False,
        ),
    ) -> Iterable[TDataItem]:
        start_date_ts = ensure_dt_type(created_at.last_value, to_ts=True)
        end_date_ts = ensure_dt_type(created_at.end_value, to_ts=True)
        yield from get_messages(channel_data, start_date_ts, end_date_ts)

    def table_name_func(channel_name: str, payload: TDataItem) -> str:
        table_type = payload.get("subtype", payload.get("type", ""))
        return f"{channel_name}_{table_type}"

    @dlt.resource(
        name="access_logs",
        selected=False,
        primary_key="user_id",
        write_disposition="append",
    )
    def logs_resource() -> Iterable[TDataItem]:
        for page_data in api.get_pages(
            resource="team.accessLogs",
            response_path="$.logins[*]",
            datetime_fields=["date_first", "date_last"],
            params={"before": end_dt if end_dt is None else end_dt.int_timestamp},
        ):
            yield page_data

    yield from (channels_resource, users_resource, logs_resource)

    if table_per_channel:
        for channel in fetched_selected_channels:
            channel_name = channel["name"]
            table_name = partial(table_name_func, channel_name)
            messages_channel = dlt.resource(
                per_table_messages_resource,
                name=channel_name,
                table_name=table_name,
                primary_key=("channel", "ts"),
                write_disposition=write_disposition,
                columns={"blocks": {"data_type": "json"}},
            )(channel)

            yield messages_channel
            if replies:
                yield messages_channel | dlt.transformer(
                    get_thread_replies,
                    name=channel_name + "_replies",
                    table_name=partial(table_name_func, channel_name + "_replies"),
                    primary_key=("thread_ts", "ts"),
                    write_disposition=write_disposition,
                )
    else:
        yield messages_resource
        if replies:
            yield messages_resource | dlt.transformer(
                get_thread_replies,
                name="replies",
                primary_key=("thread_ts", "ts"),
                write_disposition=write_disposition,
            )
